
img_root: './datasets/bdd100k'
label_root: './datasets/det_annotations'
darea_root: './datasets/da_seg_annotations'
lane_root: './datasets/ll_seg_annotations'

rgb_mean: [0.485, 0.456, 0.406]
rgb_std: [0.229, 0.224, 0.225]

categories: ['car', 'bus', 'truck', 'train']
orig_image_size: [720, 1280]
input_size: [640, 384]
#anchor_ratios: [[0.62, 1.58], [1.0, 1.0], [1.58, 0.62]]
#anchor_scales: [1, 1.6245, 2.49666] #[2**0, 2**0.70, 2**1.32]
anchors_scales: '[2**0, 2**0.70, 2**1.32]'
anchors_ratios: '[(0.62, 1.58), (1.0, 1.0), (1.58, 0.62)]'

seg_list: ['road','lane']

save_path: './checkpoint/'
img_path: './sample_images/'
batch_size: 10
